import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ToastContainer } from "react-toastify";
import TopBar from "./components/TopBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className + " bg-main-bg"}>
        <TopBar />
        <main className="container h-screen w-screen mx-auto pt-10">
          {children}
        </main>
        <ToastContainer autoClose={3000} theme="light" />
      </body>
    </html>
  );
}
